//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/trello;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Boards _Boards = new Boards();

		public Boards Boards
		{
			get
			{
				return this._Boards;
			}
		}

		private Cards _Cards = new Cards();

		public Cards Cards
		{
			get
			{
				return this._Cards;
			}
		}

		private BoardCard _BoardCard = new BoardCard();

		public BoardCard BoardCard
		{
			get
			{
				return this._BoardCard;
			}

			set
			{
				if (this._BoardCard != value)
				{
					this._BoardCard = value;
					this.OnPropertyChanged("BoardCard");
				}
			}
		}
	}

	public class Boards : System.Collections.ObjectModel.ObservableCollection<BoardsItem>
	{ 
	}

	public class BoardsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _Id = 0;

		public double Id
		{
			get
			{
				return this._Id;
			}

			set
			{
				if (this._Id != value)
				{
					this._Id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}

		private string _Desc = string.Empty;

		public string Desc
		{
			get
			{
				return this._Desc;
			}

			set
			{
				if (this._Desc != value)
				{
					this._Desc = value;
					this.OnPropertyChanged("Desc");
				}
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private bool _IsPrivate = false;

		public bool IsPrivate
		{
			get
			{
				return this._IsPrivate;
			}

			set
			{
				if (this._IsPrivate != value)
				{
					this._IsPrivate = value;
					this.OnPropertyChanged("IsPrivate");
				}
			}
		}

		private bool _Pinned = false;

		public bool Pinned
		{
			get
			{
				return this._Pinned;
			}

			set
			{
				if (this._Pinned != value)
				{
					this._Pinned = value;
					this.OnPropertyChanged("Pinned");
				}
			}
		}
	}

	public class Cards : System.Collections.ObjectModel.ObservableCollection<CardsItem>
	{ 
	}

	public class CardsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private Labels _Labels = new Labels();

		public Labels Labels
		{
			get
			{
				return this._Labels;
			}
		}

		private Members _Members = new Members();

		public Members Members
		{
			get
			{
				return this._Members;
			}
		}

		private double _Id = 0;

		public double Id
		{
			get
			{
				return this._Id;
			}

			set
			{
				if (this._Id != value)
				{
					this._Id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}

		private string _Desc = string.Empty;

		public string Desc
		{
			get
			{
				return this._Desc;
			}

			set
			{
				if (this._Desc != value)
				{
					this._Desc = value;
					this.OnPropertyChanged("Desc");
				}
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private double _Votes = 0;

		public double Votes
		{
			get
			{
				return this._Votes;
			}

			set
			{
				if (this._Votes != value)
				{
					this._Votes = value;
					this.OnPropertyChanged("Votes");
				}
			}
		}

		private bool _Voted = false;

		public bool Voted
		{
			get
			{
				return this._Voted;
			}

			set
			{
				if (this._Voted != value)
				{
					this._Voted = value;
					this.OnPropertyChanged("Voted");
				}
			}
		}

		private double _CheckItems = 0;

		public double CheckItems
		{
			get
			{
				return this._CheckItems;
			}

			set
			{
				if (this._CheckItems != value)
				{
					this._CheckItems = value;
					this.OnPropertyChanged("CheckItems");
				}
			}
		}

		private double _CheckItemsChecked = 0;

		public double CheckItemsChecked
		{
			get
			{
				return this._CheckItemsChecked;
			}

			set
			{
				if (this._CheckItemsChecked != value)
				{
					this._CheckItemsChecked = value;
					this.OnPropertyChanged("CheckItemsChecked");
				}
			}
		}

		private string _Due = string.Empty;

		public string Due
		{
			get
			{
				return this._Due;
			}

			set
			{
				if (this._Due != value)
				{
					this._Due = value;
					this.OnPropertyChanged("Due");
				}
			}
		}
	}

	public class Labels : System.Collections.ObjectModel.ObservableCollection<LabelsItem>
	{ 
	}

	public class LabelsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Color = string.Empty;

		public string Color
		{
			get
			{
				return this._Color;
			}

			set
			{
				if (this._Color != value)
				{
					this._Color = value;
					this.OnPropertyChanged("Color");
				}
			}
		}
	}

	public class Members : System.Collections.ObjectModel.ObservableCollection<MembersItem>
	{ 
	}

	public class MembersItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private System.Windows.Media.ImageSource _ImageUri = null;

		public System.Windows.Media.ImageSource ImageUri
		{
			get
			{
				return this._ImageUri;
			}

			set
			{
				if (this._ImageUri != value)
				{
					this._ImageUri = value;
					this.OnPropertyChanged("ImageUri");
				}
			}
		}
	}

	public class BoardCard : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private double _Votes = 0;

		public double Votes
		{
			get
			{
				return this._Votes;
			}

			set
			{
				if (this._Votes != value)
				{
					this._Votes = value;
					this.OnPropertyChanged("Votes");
				}
			}
		}

		private double _CheckItems = 0;

		public double CheckItems
		{
			get
			{
				return this._CheckItems;
			}

			set
			{
				if (this._CheckItems != value)
				{
					this._CheckItems = value;
					this.OnPropertyChanged("CheckItems");
				}
			}
		}

		private double _CheckItemsChecked = 0;

		public double CheckItemsChecked
		{
			get
			{
				return this._CheckItemsChecked;
			}

			set
			{
				if (this._CheckItemsChecked != value)
				{
					this._CheckItemsChecked = value;
					this.OnPropertyChanged("CheckItemsChecked");
				}
			}
		}

		private string _Due = string.Empty;

		public string Due
		{
			get
			{
				return this._Due;
			}

			set
			{
				if (this._Due != value)
				{
					this._Due = value;
					this.OnPropertyChanged("Due");
				}
			}
		}

		private Labels1 _Labels = new Labels1();

		public Labels1 Labels
		{
			get
			{
				return this._Labels;
			}
		}
	}

	public class LabelsItem1 : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Color = string.Empty;

		public string Color
		{
			get
			{
				return this._Color;
			}

			set
			{
				if (this._Color != value)
				{
					this._Color = value;
					this.OnPropertyChanged("Color");
				}
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}
	}

	public class Labels1 : System.Collections.ObjectModel.ObservableCollection<LabelsItem1>
	{ 
	}
#endif
}
