//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/trello;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Boards _Boards = new Boards();

		public Boards Boards
		{
			get
			{
				return this._Boards;
			}
		}
	}

	public class Boards : System.Collections.ObjectModel.ObservableCollection<BoardsItem>
	{ 
	}

	public class BoardsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _Id = 0;

		public double Id
		{
			get
			{
				return this._Id;
			}

			set
			{
				if (this._Id != value)
				{
					this._Id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}

		private string _Desc = string.Empty;

		public string Desc
		{
			get
			{
				return this._Desc;
			}

			set
			{
				if (this._Desc != value)
				{
					this._Desc = value;
					this.OnPropertyChanged("Desc");
				}
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private bool _IsPrivate = false;

		public bool IsPrivate
		{
			get
			{
				return this._IsPrivate;
			}

			set
			{
				if (this._IsPrivate != value)
				{
					this._IsPrivate = value;
					this.OnPropertyChanged("IsPrivate");
				}
			}
		}

		private bool _Pinned = false;

		public bool Pinned
		{
			get
			{
				return this._Pinned;
			}

			set
			{
				if (this._Pinned != value)
				{
					this._Pinned = value;
					this.OnPropertyChanged("Pinned");
				}
			}
		}
	}
#endif
}
